//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probasem
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Должность.
    /// </summary>
    // *** Start programmer edit section *** (Должность CustomAttributes)

    // *** End programmer edit section *** (Должность CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДолжностьE", new string[] {
            "КодДолжности as \'Код должности\'",
            "НаимДолжности as \'Должность\'",
            "Карта as \'Карта\'",
            "Карта.КодКарты as \'Код карты\'"}, Hidden=new string[] {
            "Карта.КодКарты"})]
    [MasterViewDefineAttribute("ДолжностьE", "Карта", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "КодКарты")]
    [View("ДолжностьL", new string[] {
            "КодДолжности as \'Код должности\'",
            "НаимДолжности as \'Должность\'",
            "Карта.КодКарты as \'Код карты\'"})]
    public class Должность : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодДолжности;
        
        private string fНаимДолжности;
        
        private IIS.Probasem.Карта fКарта;
        
        // *** Start programmer edit section *** (Должность CustomMembers)

        // *** End programmer edit section *** (Должность CustomMembers)

        
        /// <summary>
        /// КодДолжности.
        /// </summary>
        // *** Start programmer edit section *** (Должность.КодДолжности CustomAttributes)

        // *** End programmer edit section *** (Должность.КодДолжности CustomAttributes)
        public virtual int КодДолжности
        {
            get
            {
                // *** Start programmer edit section *** (Должность.КодДолжности Get start)

                // *** End programmer edit section *** (Должность.КодДолжности Get start)
                int result = this.fКодДолжности;
                // *** Start programmer edit section *** (Должность.КодДолжности Get end)

                // *** End programmer edit section *** (Должность.КодДолжности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должность.КодДолжности Set start)

                // *** End programmer edit section *** (Должность.КодДолжности Set start)
                this.fКодДолжности = value;
                // *** Start programmer edit section *** (Должность.КодДолжности Set end)

                // *** End programmer edit section *** (Должность.КодДолжности Set end)
            }
        }
        
        /// <summary>
        /// НаимДолжности.
        /// </summary>
        // *** Start programmer edit section *** (Должность.НаимДолжности CustomAttributes)

        // *** End programmer edit section *** (Должность.НаимДолжности CustomAttributes)
        [StrLen(255)]
        public virtual string НаимДолжности
        {
            get
            {
                // *** Start programmer edit section *** (Должность.НаимДолжности Get start)

                // *** End programmer edit section *** (Должность.НаимДолжности Get start)
                string result = this.fНаимДолжности;
                // *** Start programmer edit section *** (Должность.НаимДолжности Get end)

                // *** End programmer edit section *** (Должность.НаимДолжности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должность.НаимДолжности Set start)

                // *** End programmer edit section *** (Должность.НаимДолжности Set start)
                this.fНаимДолжности = value;
                // *** Start programmer edit section *** (Должность.НаимДолжности Set end)

                // *** End programmer edit section *** (Должность.НаимДолжности Set end)
            }
        }
        
        /// <summary>
        /// Должность.
        /// </summary>
        // *** Start programmer edit section *** (Должность.Карта CustomAttributes)

        // *** End programmer edit section *** (Должность.Карта CustomAttributes)
        [PropertyStorage(new string[] {
                "Карта"})]
        [NotNull()]
        public virtual IIS.Probasem.Карта Карта
        {
            get
            {
                // *** Start programmer edit section *** (Должность.Карта Get start)

                // *** End programmer edit section *** (Должность.Карта Get start)
                IIS.Probasem.Карта result = this.fКарта;
                // *** Start programmer edit section *** (Должность.Карта Get end)

                // *** End programmer edit section *** (Должность.Карта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должность.Карта Set start)

                // *** End programmer edit section *** (Должность.Карта Set start)
                this.fКарта = value;
                // *** Start programmer edit section *** (Должность.Карта Set end)

                // *** End programmer edit section *** (Должность.Карта Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДолжностьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностьE", typeof(IIS.Probasem.Должность));
                }
            }
            
            /// <summary>
            /// "ДолжностьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностьL", typeof(IIS.Probasem.Должность));
                }
            }
        }
    }
}
